### ISSUE TITLE
Read Configuration File

### ISSUE THREAD

**Issue by dendeaisd** [dendeaisd/Webserv#28]
- [ ] The configuration file is read from the command-line argument or default path
- [ ] Errors are handled if the file is missing, is inaccessible or has incorrect permissions 
- [ ] **Unit test:** Test with valid and invalid file paths, permissions and file formats

**Comment by fritz-gabler** [comment]
> * [ ]  The configuration file is read from the command-line argument or default path
> * [ ]  Errors are handled if the file is missing, is inaccessible or has incorrect permissions
> * [ ]  **Unit test:** Test with valid and invalid file paths, permissions and file formats

**Comment by fritz-gabler** [comment]
File input check
> * [ ]  A function checks if the configuration file passed as an argument can be opened
> * [ ]  There is a check that make sure that for every opening braked  closing one exists
> * [ ]  


> * [ ]  The configuration file is read from the command-line argument or default path
> * [ ]  Errors are handled if the file is missing, is inaccessible or has incorrect permissions
> * [ ]  **Unit test:** Test with valid and invalid file paths, permissions and file formats
